name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
schedule:
    - cron: '*/5 * * * *'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, dom, curl, libxml, mysql
        coverage: xdebug

    - name: Install Dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    - name: Prepare Environment
      run: |
        cp .env.example .env
        php artisan key:generate
    - name: Run Migrations
      run: |
        php artisan config:clear
        php artisan migrate --force --database=mysql
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel_db
        DB_USERNAME: root
        DB_PASSWORD: ""

    - name: Execute Tests
      run: vendor/bin/phpunit
